# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"collapse_whitespace": "01_text_norm.ipynb",
         "lowercase": "01_text_norm.ipynb",
         "check_no_numbers": "01_text_norm.ipynb",
         "remove_specials": "01_text_norm.ipynb",
         "expand_abbreviations": "01_text_norm.ipynb",
         "unify_dash_hyphen": "01_text_norm.ipynb",
         "basic_cleaner": "01_text_norm.ipynb",
         "russian_cleaner": "01_text_norm.ipynb",
         "get_files": "02_data.ipynb",
         "get_audio_files": "02_data.ipynb",
         "get_txt_files": "02_data.ipynb",
         "words_count": "02_data.ipynb",
         "label_func": "02_data.ipynb",
         "ReadTxt": "02_data.ipynb",
         "word_in_files": "02_data.ipynb",
         "regex_files": "02_data.ipynb",
         "accent_files": "02_data.ipynb",
         "plot_durations": "02_data.ipynb",
         "drop_outliers": "02_data.ipynb"}

modules = ["text_norm.py",
           "data.py"]

doc_url = "https://kdorichev.github.io/text2speech/"

git_url = "https://github.com/kdorichev/text2speech/tree/master/"

def custom_doc_links(name): return None
