# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"collapse_whitespace": "01_text_norm.ipynb",
         "lowercase": "01_text_norm.ipynb",
         "check_no_numbers": "01_text_norm.ipynb",
         "remove_specials": "01_text_norm.ipynb",
         "expand_abbreviations": "01_text_norm.ipynb",
         "basic_cleaner": "01_text_norm.ipynb",
         "russian_cleaner": "01_text_norm.ipynb"}

modules = ["text_norm.py"]

doc_url = "https://kdorichev.github.io/text2speech/"

git_url = "https://github.com/kdorichev/text2speech/tree/master/"

def custom_doc_links(name): return None
